server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/a-shop
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:db.migration/db.changelog-master.xml
    driver-class-name: org.postgresql.Driver
    database-change-log-lock-table: LIQ_DATABASECHANGELOGLOCK
    database-change-log-table: LIQ_DATABASECHANGELOG

  kafka:
    bootstrap-servers: localhost:29092
